# Meta Data for SEO

## Homepage
title = "GoTuna"
titleSeparator = "-"
titleAddition = "Progressive web framework written in Go"
description = "GoTuna - progressive web framework written in Go"

## Open Graph + Twitter Cards
images = ["gotuna-card.jpeg"]
#twitterSite = "henkverlinde"
#twitterCreator = "henkverlinde"
#facebookAuthor = "verlinde.henk"
#facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "GoTuna"
schemaLogo = "logo-gotuna.png"
#schemaTwitter = "https://twitter.com/henkverlinde"
#schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
#schemaGitHub = "https://github.com/h-enk"
#schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://interactive32.com\">Interactive32</a>"

# Alert
alert = false
alertText = "Like GoTuna? <a class=\"alert-link\" href=\"https://github.com/gotuna/gotuna\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/gotuna/docs"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
